spring.application.name=projetoComDestinoIndefinido

spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=username
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

server.port=7443
server.port.http=7080

projetoComDestinoIndefinido.frontendUrl=${FRONTEND_URL}
projetoComDestinoIndefinido.authKeySecret=${AUTH_KEY_SECRET}

server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1.2